### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by VelvetWanderer** [wetstreet/Theircraft#23]

**Comment by wetstreet** [comment]
can you please tell me what information i should add to readme? thanks

**Comment by VelvetWanderer** [comment]
the instructions for contributing are not very clear.

**Comment by VelvetWanderer** [comment]
the project files are confusing, too.

**Comment by wetstreet** [comment]
ok, I'll try to fix that, thanks

**Comment by VelvetWanderer** [comment]
thank you!

**Comment by VelvetWanderer** [comment]
have a good one,
