### ISSUE TITLE
complier error

### ISSUE THREAD

**Issue by Hello-Grow** [wetstreet/Theircraft#26]
![image](https://github.com/wetstreet/Theircraft/assets/100985153/cd27cee1-ebbd-4e7c-934d-fa60c453ba86) i keep getting these errors how do I fix this? im using unity version2021.1.12f1

**Comment by dcmrobin** [comment]
I'm not sure if this will work or not, but the thing I do to fix the problems with packages is just uninstall them and install them again. (As it seems the problem has to do with the Universal Render Pipeline)

**Comment by Hello-Grow** [comment]
ok I figured it out thanks!
